parameters:
  # defaults, if not specified
  configuration: 'Release'

steps:
  - bash: |
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=${{ parameters.configuration }} ..
    make
    ctest
  displayName: 'Building'
#  - script: cd makefiles && make config=${{ parameters.configuration }}
